### ISSUE TITLE
length dial number for click2call

### ISSUE THREAD

**Issue by Alexua1** [ZeXtras/universal-dialer#6]
My Asterisk uses three digits in telephone number. 
When using Zimlet universal-dialer, three-place numbers phone not active for Click2Call.
Сan You  add this function ?

**Comment by StefanoGrasselli** [comment]
Hi Alexua,
three digits numbers are very common and has been chosen to not match them.
However you can add them changing org_zetalliance_universaldialer.xml regex with a more relaxed one. 
E.g:
```xml
((\/| |\.|\-)?((\(\+?\d{1,4}\))|(\d{2,4}))){1,5}(=?((\.|\,)?(\n|\r\n|\s|\t|$)))
```

**Comment by Alexua1** [comment]
thanks a lot


5 апр. 2017 г. 17:29 пользователь "StefanoGrasselli" <
notifications@github.com> написал:

**Comment by Alexua1** [comment]
Thanks a lot.
Its work

2017-04-05 17:29 GMT+03:00 StefanoGrasselli <notifications@github.com>:
